---
- name: restart nut driver
  service:
    name: nut-driver
    state: restarted
  when: nut_enable_service and nut_mode == 'standalone'

- name: restart nut monitor
  service:
    name: nut-monitor
    state: restarted
  when: nut_enable_service

- name: restart nut server
  service:
    name: nut-server
    state: restarted
  when: nut_enable_service and nut_mode == 'standalone'